# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 497e925e80e78212c390a853e2cec30ded3c895c404c4b3fcac80e92c50a62081cd768830cd623ceefe8b7afb2bd7c0c9b4443871d3d6e511a0bd7f7f599d50e

test:
  secret_key_base: e510d7f45dd4e92a3dc4667e81e4f72dcbbe47c8815184739973ba46d1236a0d65208bb588992ff29c7f512238dd344b1971d7b2e7ae2860969c3b5c13d47738

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
